### ISSUE TITLE
Stack trace on PUT for collections

### ISSUE THREAD

**Issue by dstockto** [zfcampus/zf-content-negotiation#41] opened 2015-05-05 23:10 UTC
If you PUT to a collection URI something that isn't an array you get a 500 Internal server error and a stack trace. It should probably be a 400 with an error but no stack trace.

**Comment by weierophinney** [comment] 2015-07-08 21:22
Is this still true? v1.0.5 had a fix for #35 that likely fixes this, but I'm not 100% certain. Are you still seeing the problem today, @dstockto ?

**Comment by dstockto** [comment] 2015-07-09 05:28
Yes, as far as I can remember for the repro steps. 

I just tried this running v1.0.7 and was able to get a 500 with a stack trace by sending in a JSON object with a random key/value into a collection PUT URI.

**Comment by weierophinney** [comment] 2015-07-09 13:33
@dstockto I've just tested, and the situation is definitely resolved in the latest versions.

**Comment by weierophinney** [comment] 2015-07-09 16:44
Per @dstockto in IRC, the issue found was specifically when sending an object to PUT for a collection.

**Comment by weierophinney** [comment] 2015-07-09 16:51
I've recreated the issue with the following payload:

```json
{
  "foo": "bar"
}
```

This returns a 500 status, with a problem detail indicating the issue. However, it should return a 400, and likely no stack trace; the issue is the client is sending an invalid data structure.

**Comment by weierophinney** [comment] 2015-07-09 19:08
The issue is in zf-rest, as the checks for array or object are done in the `Resource` class:

- https://github.com/zfcampus/zf-rest/blob/93c1f31835519232cad986e35a9ca38eb6f5ef4c/src/Resource.php#L314-L319
- https://github.com/zfcampus/zf-rest/blob/93c1f31835519232cad986e35a9ca38eb6f5ef4c/src/Resource.php#L402-L407

I'll update those exceptions to use a 400 status code.

**Closed** 2015-07-09 19:21 UTC
Labels: bug
